server:
  port: 0
spring:
  application:
    name: loan-service
  cloud:
    config:
      enabled: true
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    info:
      enabled: true
    web:
      exposure:
        include: "*"

